adding routes logic
WildCodeSchool-2024-02/JS-LILLE-0224-P2-G1-brewcat pull request #11
Opened 2024-04-18 09:56 UTC by alexandreLebeau

j'ai ajouté les routes, la navbar est fonctionnelle sur les 2 versions du site :)

2024-04-18 10:27 UTC, MathieuDelfosse approved these changes

2024-04-18 13:31 UTC, BENOITMEZAGUER approved these changes
Well done!

2024-04-19 07:27 UTC, fantinerudent commented on client/src/components/Navbar/Navbar.jsx
> +          <a href="http://localhost:3000//" className="link_backhome">
why the "//"

2024-04-19 07:28 UTC, fantinerudent commented on client/src/components/Navbar/Navbar.jsx
> +                {/* <a href="/RandomBeer">Random Beer</a> */}
dead code

2024-04-19 07:28 UTC, alexandreLebeau commented on client/src/components/Navbar/Navbar.jsx
> +          <a href="http://localhost:3000//" className="link_backhome">
it's a mistake

2024-04-19 07:29 UTC, fantinerudent requested changes
see the comments

2024-04-19 07:36 UTC, alexandreLebeau commented
CORRECTED

2024-04-19 07:53 UTC, fantinerudent approved these changes

2024-04-19 09:00 UTC, merged