Us09 carousel
WildCodeSchool-2024-02/JS-LILLE-0224-P2-G1-brewcat pull request #15
Opened 2024-04-19 10:08 UTC by BENOITMEZAGUER

Pwease check my pull wequest

2024-04-19 13:13 UTC, eloregnier requested changes
supprimer le stylesheet en trop

2024-04-19 13:13 UTC, eloregnier commented on client/index.html
>        rel="stylesheet"
supprimer ce rel=stylesheet

2024-04-23 09:49 UTC, eloregnier commented on client/src/App.jsx
Il faudra qu'on ajoute le carousel a Home Page avec les routes, mais la c'est OK

2024-04-23 09:50 UTC, eloregnier approved these changes

2024-04-23 13:27 UTC, fantinerudent approved these changes
good job!

2024-04-24 09:20 UTC, merged