Error page done
WildCodeSchool-2024-02/JS-LILLE-0224-P2-G1-brewcat pull request #16
Opened 2024-04-24 09:22 UTC by BENOITMEZAGUER

Error page created with responsive and finished

2024-04-24 10:27 UTC, eloregnier approved these changes

2024-04-24 12:05 UTC, fantinerudent requested changes

2024-04-24 12:05 UTC, fantinerudent commented on client/src/components/NotFound/NotFound.jsx
> +      {/* Conteneur de la page d'erreur */}
pourquoi les commentaires sont en anglais partout sauf sur ce composant ?

2024-04-25 13:57 UTC, fantinerudent approved these changes

2024-04-25 14:01 UTC, merged