Card css and API import ok
WildCodeSchool-2024-02/JS-LILLE-0224-P2-G1-brewcat pull request #5
Opened 2024-04-11 14:19 UTC by eloregnier

2024-04-11 14:30 UTC, alexandreLebeau approved these changes
good for me. Maybe we need to comment more our code :)

2024-04-12 07:16 UTC, fantinerudent requested changes
il faut que tu corriges mes retours sur ta branche,
que tu fasses un nouveau commit avec les modifs, et que tu me repingues quand les changements ont été fait ! :)

2024-04-12 07:16 UTC, fantinerudent commented on client/src/components/Cards/Card.jsx
> +function Card({ Beer }) {
lowercase pleaseeee ( et sur le reste du composant aussi que Beer devienne beer )

2024-04-12 07:16 UTC, fantinerudent commented on client/src/App.jsx
> +  // `https://beers.utop.workers.dev/beers?abv_min=${choixduuser}`
delete comment

2024-04-12 07:16 UTC, fantinerudent commented on client/index.html
> +
useless line

2024-04-12 07:51 UTC, fantinerudent approved these changes

2024-04-12 07:55 UTC, merged