adding footer
WildCodeSchool-2024-02/JS-LILLE-0224-P2-G1-brewcat pull request #6
Opened 2024-04-12 09:24 UTC by Vinz2406

Creation of the footer with addition of Footer.jsx and Footer.css files

2024-04-12 09:30 UTC, alexandreLebeau requested changes

2024-04-12 09:30 UTC, alexandreLebeau commented on client/src/components/Footer.css
> +.social_networks .fa-icon:hover {
replace .fa-icon with .fa_icon

2024-04-12 13:50 UTC, fantinerudent approved these changes

2024-04-12 13:50 UTC, fantinerudent commented on client/src/App.jsx
> +
useless empty line

2024-04-15 09:14 UTC, alexandreLebeau commented
all good

2024-04-15 09:24 UTC, alexandreLebeau approved these changes
all good

2024-04-15 09:24 UTC, merged